name: "Hello Actions"
description: "Greet someone"
author: "FaisalAfroz@github.com"

inputs:
  MY_NAME:
    description: "Whom to greet?"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
